name = "PacificNobleGasRelic"
authors = ["G Jake Gebbie"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TMItransient = "ab8155c7-aa61-46aa-9e27-6244078cebd2"

[compat]
DrWatson = "2.9.1"
julia = "1.7.2"
